// Code generated by protoc-gen-micro. DO NOT EDIT.

package foo

import (
  "context"
  "github.com/ofavor/micro-lite/server"
  "github.com/ofavor/micro-lite/client"
)

type FooService interface {
  Bar(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type fooService struct {
  serviceName string
  c client.Client
}

func NewFooService(name string, c client.Client) FooService {
  return &fooService {
    serviceName: name,
    c: c,
  }
}

func (s *fooService)Bar(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
  req := client.NewRequest(s.serviceName, "Foo.Bar", in)
  rsp := new(Response)
  err := s.c.Call(ctx, req, rsp, opts...)
  if err != nil {
    return nil, err
  }
  return rsp, nil
}

type FooHandler interface {
  Bar(ctx context.Context, in *Request, out *Response) error
}

func RegisterFooHandler(s server.Server, h FooHandler) {
  hdr := server.NewHandler("Foo", h)
  s.Handle(hdr)
}

