version: '3'

services:
  etcd:
    image: bitnami/etcd:3.4.14
    environment: 
      - TZ=Asia/Shanghai
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    # ports:
    #   - 2379:2379
    #   - 2380:2380


  simple-server:
    image: dkfbasel/hot-reload-go:1.14.2
    volumes:
      # mount the project into the docker container. Please note, that the
      # app directory is symlinked into the project path specified as
      # environment variable. For goconvey to work, the package must be
      # linked directly into the the package directory i.e. /go/src/[PROJECTPATH]
      - ./:/app
    environment: 
      - TZ=Asia/Shanghai
      # directory to look for the main go entry point (default: /app)
      - DIRECTORY=/app/examples/simple/server
      # specify the command that should be run, can be 'build' or 'test'
      # 'build' is the default command 
      - CMD=build
      # arguments can be used to specify arguments to pass to the executable
      # on running
      - ARGS=-registry_addrs=etcd:2379
    depends_on: 
      - etcd

  simple-client:
    image: dkfbasel/hot-reload-go:1.14.2
    volumes:
      # mount the project into the docker container. Please note, that the
      # app directory is symlinked into the project path specified as
      # environment variable. For goconvey to work, the package must be
      # linked directly into the the package directory i.e. /go/src/[PROJECTPATH]
      - ./:/app
    environment: 
      - TZ=Asia/Shanghai
      # directory to look for the main go entry point (default: /app)
      - DIRECTORY=/app/examples/simple/client
      # specify the command that should be run, can be 'build' or 'test'
      # 'build' is the default command 
      - CMD=build
      # arguments can be used to specify arguments to pass to the executable
      # on running
      - ARGS=-registry_addrs=etcd:2379
    depends_on: 
      - etcd
      - simple-server